name: GENERATE A APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verify my code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3

      - name: Install all dependancy
        run : |
          npm install -g expo-cli eas-cli
          npm install
      
      - name: Build My project with EAS/Generate apk for Android Device
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

        run: |
          eas build --platform android --profile production --non-interactive